package wednes:function@0.1.0;

interface types {
  record header {
    name: string,
    value: string,
  }
  record request {
    method: string,
    path: string,
    headers: list<header>,
    body: list<u8>,
  }
  record response {
    status: u16,
    headers: list<header>,
    body: list<u8>,
  }
}

interface http-client {
  use types.{request, response};
  send-request: func(req: request) -> result<response, string>;
}

world function {
  use types.{request, response};
  import http-client;
  export handle: func(req: request) -> response;
}
